### ISSUE TITLE
Cartago feedback booleans not working in Jason namespaces

### ISSUE THREAD

**Issue by copycat-killer** [jacamo-lang/jacamo#10]
I have a Jason namespace in which an agent creates a Cartago artifact. This artifact has an operation with a `OpFeedbackParam<Boolean>` parameter. If I use the operation, the boolean I get is not seen as a logical formula in the namespace. Example:

`example.jcm`
```java
mas example {

    agent alice
    
    asl-path: src/agt, src/agt/inc
}
```

`alice.asl`
```java
!start.

+!start <- .include("bob.asl", _).
```

`bob.asl`
```java
!start.

+!start
<-
    makeArtifact("test", "example.Test");
    getTrueBoolean(B);
	
    if (B) {
        .print(B);	
    } else {
        .print("nope");
    }.
```

`src/env/example/Test.java`
```java
// [...]
public class Test extends Artifact {
    @OPERATION
    void getTrueBoolean(OpFeedbackParam<Boolean> b) {
        b.set(true);
    }
}
```

Result:

```
CArtAgO Http Server running on http://127.0.0.1:3273
Jason Http Server running on http://127.0.0.1:3272
[alice] nope
```

While if I use:

`example.jcm`
```java
mas example {

    agent bob
    
    asl-path: src/agt, src/agt/inc
}
```

I correctly get:

```
CArtAgO Http Server running on http://127.0.0.1:3273
Jason Http Server running on http://127.0.0.1:3272
[bob] true
```

Example project download: [example.zip](https://github.com/jacamo-lang/jacamo/files/1203367/example.zip)

**Comment by jomifred** [comment]
Thanks Luke for reporting this bug and the example to replicate it. 

It is related to namespaces (something new in Jason and thus not so well tested) and is fixed in Jason repository on github.

Before a new release of jason/jacamo, the workaround is to write the if as follows

    if (default::B) {

**Comment by copycat-killer** [comment]
Thanks for the bugfix.

I understand namespaces are one of the latest additions, but they've been around since at least a year by now. Because incapsulation is a desiderable feature in a productive environment, I suggest to add 

```
doing a good coverage of Jason namespaces
```

as ToDo for Jason next release.
