### ISSUE TITLE
[Suggestion] Travis CI + Coveralls

### ISSUE THREAD

**Issue by lcpz** [jacamo-lang/jacamo#16]
Hi, since you're using Gradle and have tests, I suggest to start using some automation tools, like [Better Code Hub](https://github.com/marketplace/better-code-hub) or [Codacy](https://github.com/marketplace/codacy) for code quality, and [Travis CI](https://github.com/marketplace/travis-ci) + [Coveralls](https://github.com/marketplace/coveralls) for continuous integration and coverage.

These tools simplify maintenance a lot and are a valid aid in bug hunting. Plus, they work as an informal metric of quality for your project, which in turn can get more visibility from them.

Of course, Jason, CArtAgO and Moise too should get the same treatment.

I am willing to lend a hand, if you want.

**Comment by jomifred** [comment]
Hi Luke,

thanks a lot for your suggestion! 

these tools look promising, although I am not used to them (and just now do not have time to learn them). So, if you want to take a closer look or apply them on JaCaMo… I fully support.

all the best,

Jomi

ps.: I am not sure this kind of tools are suitable to evaluate “interpreters”… but, let’s see.


> On 24 de ago de 2017, at 11:52, Luke Bonham <notifications@github.com> wrote:
> 
> Hi, since you're using Gradle and have tests, I suggest to start using some automation tools, like Better Code Hub for code quality, and Travis CI + Coveralls for continuous integration and coverage.
> 
> These tools simplify maintenance a lot and are a valid aid in bug hunting. Plus, they work as an informal metric of quality for your project, which in turn can get more visibility from them.
> 
> Of course, Jason, CArtAgO and Moise too should get the same treatment.
> 
> I am willing to lend a hand, if you want.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)

**Comment by copycat-killer** [comment]
OK, I'll start using them in my forks, which will be kept synched with your masters.

Whenever I'll found an issue or have an improvement, I'll open a PR.

If this will convince you at some point, I'll show you how to integrate the tools in the main repositories.

**Comment by jomifred** [comment]
good! thanks.

> On 25 de ago de 2017, at 05:20, Luke Bonham <notifications@github.com> wrote:
> 
> OK, I'll start using them in my forks, which will be kept synched with your masters.
> 
> Whenever I'll found an issue or have an improvement, I'll open a PR.
> 
> If this will convince you at some point, I'll show you how to integrate the tools in the main repositories.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)
