### ISSUE TITLE
jacamo and gradle

### ISSUE THREAD

**Issue by icar-aose** [jacamo-lang/jacamo#19]
Dear All,

I happily discovered the possibility to create a bacammo-gradle project (https://github.com/jacamo-lang/jacamo/blob/master/doc/tutorials/hello-world/shell-based.adoc)

So I decided to test soon this option, however gradle fails when building the project with the following message:

Could not resolve com.tilab.jade:jade:4.5.0.
      > Could not get resource 'http://jade.tilab.com/maven/com/tilab/jade/jade/4.5.0/jade-4.5.0.pom'.
         > Could not GET 'http://jade.tilab.com/maven/com/tilab/jade/jade/4.5.0/jade-4.5.0.pom'.
            > jade.tilab.com: nodename nor servname provided, or not known

I think the problem is that jade is no more in the specified maven repository. 
How to do for solving this problem?

Thanks
Luca

**Comment by jomifred** [comment]
Hi Luca,

can you check if the line

	maven { url "http://jade.tilab.com/maven/“ }

appears in the file build.gradle? (if not, just add this line in the repositories) 

thanks
-- 
Jomi Fred Hubner
Federal University of Santa Catarina
Department of Automation and Systems Engineering
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
