### ISSUE TITLE
Included file 'moiseJar' is not configured

### ISSUE THREAD

**Issue by pulverizers** [jacamo-lang/jacamo#21]
I am following the helloworld tutorial and the organization part is not working as soon as I uncomment the include line to make the agents obedient. The "hello world" is not printed as expected.

<img width="558" alt="jacamo-bug" src="https://user-images.githubusercontent.com/8087472/47052862-36da8d80-d1a2-11e8-85c6-fc5f385c0c17.PNG">

Attached is the screenshot for your reference, how to fix this? Thanks.

**Comment by pulverizers** [comment]
I've downloaded and replaced with the version but unfortunately the same problem still persists...

**Comment by jomifred** [comment]
Hum... which option (from http://jacamo.sourceforge.net/doc/install.html) are you using to run the application?

If eclipse, it is important to run (jacamo-0.7.jar) again to configure it in your machine. To run, double click on the jar file; in unix run `java -jar jacamo-0.7.jar`

**Comment by pulverizers** [comment]
I'm using eclipse. Yes i have ran the .jar again of course. Also tried reinstalling the plugin but no luck..

![image](https://user-images.githubusercontent.com/8087472/47091661-33d0b300-d21d-11e8-81e9-298b302a44f5.png)

**Comment by jomifred** [comment]
I reproduced the error here (in eclipse) and (at least here) fixed it. New release of jacamo (0.7b) at
	https://sourceforge.net/projects/jacamo/files/version-0

Please, let me know if it works for you now.

> On 17 Oct 2018, at 11:00, bangxiang <notifications@github.com> wrote:
> 
> I'm using eclipse. Yes i have ran the .jar again of course. Also tried reinstalling the plugin but no luck..
> 
> 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Jomi Fred Hubner
Department of Automation and Systems Engineering
Federal University of Santa Catarina
PO Box 476, Florianópolis, SC
88040-900 Brazil
http://jomi.das.ufsc.br
-- 
be good. be kind. be happy. (Conrad Anker)

**Comment by pulverizers** [comment]
yes, works like a charm now! thanks for your quick action, well done!

now i can proceed to continue exploring jacamo ;)

**Comment by jomifred** [comment]
Good! Thanks again for reporting the problem.

We are trying to move to Gradle to avoid local configuration problems. If you are using Eclipse Photon, you can use the menu "File/Import" then "Existing Gradle Project" and select the hello world directory. Eclipse will looks like

<img width="247" alt="screen shot 2018-10-17 at 11 56 20" src="https://user-images.githubusercontent.com/78732/47095582-e98f0800-d203-11e8-9e57-66a015f1657e.png">

You can run the application by clicking on the task "run" of gradle tab... . it will download all necessary dependencies.
