### ISSUE TITLE
namespaces are not working when the belief comes from CArtAgO defineObsProperty method

### ISSUE THREAD

**Issue by cleberjamaral** [jacamo-lang/jacamo#23]
When invoked, for example, defineObsProperty("topic::element", 0), Jason actually creates a belief as "topic::element(0)" instead of a namespace "topic" with "element(0)" belief.

**Comment by cleberjamaral** [comment]
Here an example:
introduceyourself[...].
expertise(vivt4)[...].
lastquotation(37.68)[...].
stock::datequotation("29 Oct. 2018 17:09")[...].
stock::lastquotation(37.68)[...].
stock::sourcequotation("uol")[...].
focused(main,stockbot3[...],cobj_3)[...].
focused(main,telegrambot3[...],cobj_2)[...].

stock:: 
expertise(vivt4)[...].
threshold(43.00)[...].

telegram:: 
chatIdTelegram("-274694619")[...].
expertMenu(["IntroduceYourself","Quotation","SetExpertise","SetThreshold","RecreateArtifact"])[...].

**Comment by jomifred** [comment]
It shouldn't work. Namespaces are concepts for the agent dimension. Different agents can focus on the same artefact and place its obs. props. in different namespaces. 

to define the namespace for some artefact, the focus operation can be prefixed with the namespace

`home::focus(ArtId)`
