### ISSUE TITLE
[Question] Comparison between JADE and JaCaMo

### ISSUE THREAD

**Issue by copycat-killer** [jacamo-lang/jacamo#9]
Is there a comparison explaining pros and cons of both frameworks? Or maybe are there some specific references from which we can extrapolate it?

Having such knowledge would surely benefit both project and potential users.

In case, under your guide, I am willing to help writing this documentation.

**Comment by copycat-killer** [comment]
I wrote something.

---

JADE is a middleware implementing a P2P approach which allows agent to communicate and work in a distributed way. The middleware and agent functionalities are implemented in Java, so all the programming is done uniquely in this language. JADE development started in 1998, the code went open source in 2000, and a governing commitee was started in 2003 in order to facilitate the development and promotion of JADE. Since then, it has been used in a lot of industrial and government projects, thus becoming the de facto standard for agent distribution and communication.

JaCaMo is a meta-framework implemented in Java. Its approach defines various levels of abstraction, each building on the underlying one, as depicted in the following figure ([source](http://jacamo.sourceforge.net/?page_id=40)).

<div align="center">
<img src="http://jacamo.sourceforge.net/wordpress/wp-content/uploads/2011/05/jacamo_approach.png">
</div

Levels 1 to 3 are provided by Cartago, Jason and Moise, respectively. Level 0 can be provided by different frameworks, which are:

* `centralised`: all agents and artifacts execute on local host;
* `cartago`: artifacts on local host can be made accessible to remote agents;
* `jade`: agents and artifacts can execute in a distributed environment;
* programmer-defined variants.

Programming in JaCaMo is done in Java and an extension of AgentSpeak. Java choice is obvious (open source, large industry adoption); AgentSpeak has been chosen because it's based on logic programming and the BDI architecture for cognitive autonomous agents, so it provides the most natural paradigm for MAS. The AgentSpeak extension used is a much improved version of the original, including also speech-act based inter-agent communication.

The JADE objectives are to provide a fully distributed, FIPA compliant middleware for agents, especially based on efficient transport of asynchronous messages, mobility (agents and code can migrate between processes and machines) and interaction protocols.

The JaCaMo main objective is to provide a framework for Multi-Agent Oriented Programming ([MAOP](http://jacamo.sourceforge.net/tutorial/index.html)), which can also run on top of JADE, thus combining the best of both technologies.

**Comment by rbordini** [comment]
that's very well written, Luke.

cheers

**Comment by copycat-killer** [comment]
Anyone who knows JADE a bit should see the difference. My previous post can give a quick hint about it, but if someone wants a complete comparison, he/she "just" have to read JADE programming reference book and academic papers on JaCaMo referenced on the main site.
